{% set name = "qmflows" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qmflows-{{ version }}.tar.gz
  sha256: c4b3ba80345d7cb921b582d27c2597caa27d4890067be74de103dec15f9ed5a5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - filelock
    - h5py
    - more-itertools
    - noodles >=0.3.3
    - numpy >=1.21,<2
    - packaging >=1.16.8
    - pandas
    - plams ==1.5.1
    - pyparsing !=3.0.0,<3.1.0
    - python >=3.6
    - pyyaml >=5.1

test:
  imports:
    - qmflows
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SCM-NV/qmflows
  summary: Automation of computations in quantum chemistry
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
